swagger: "2.0"
info:
  description: "API Task"
  version: "1.0.0"
  title: "Todos project API"
host: "localhost:5000"
basePath: "/"
tags:
- name: "todo"
  description: "Everything about your todos"
schemes:
- "https"
- "http"
paths:
  /todo:
    get:
      summary: "Get all todos"
      operationId: "getTodos"
      tags:
      - "todo"
      responses:
        "200":
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Todo"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
      - "todo"
      summary: "Add a new todo"
      description: ""
      operationId: "addTodo"
      parameters:
      - in: "body"
        name: "body"
        description: "Todo object that needs to be added to the store"
        required: true
        schema:
          type: "object"
          properties:
            text:
              type: "string"
              description: "The todo title"
      responses:
         "201":
          description: "Todo added successfully"
          schema:
            $ref: "#/definitions/Todo"
         "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
  /todo/{id}:
    put:
      tags:
      - "todo"
      summary: "Update an existing todo"
      description: ""
      operationId: "updateTodo"
      parameters:
      - name: "id"
        in: "path"
        description: "Id of todo to update"
        required: true
        type: "integer"
      responses:
        "200":
            description: "Todo updated successfully"
            schema:
              $ref: "#/definitions/Todo"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"


definitions:
  Todo:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      text:
        type: "string"
      done:
        type: "boolean"

  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      details:
        type: "string"

   